default_config:
logger:
  default: error
  logs:
    custom_components.myfitnesspal: debug



myfitnesspal:
  username: my_username
  password: my_password
  sensor:
    - enabled: true
      name: My custom name
